/*
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 \ Empresa.: PresServ Inform tica-Limeira (019)452.6623
 \ Programa: R03001F9.PRG
 \ Data....: 02-08-96
 \ Sistema.: Administradora de Funer rias
 \ Funcao..: N' OP. do relat¢rio ADM_R030
 \ Analista: Ademilson Pedro Bom
 \ Criacao.: Programado manualmente pelo analistad
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
*/

#include "adrbig.ch"    // inicializa constantes manifestas

nucop:=2
RETU []       // <- deve retornar um valor qualquer

* \\ Final de R03001F9.PRG
