
procedure r03001f9
/*
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 \ Empresa.: Presserv Informatica Ltda (19)99886.3225
 \ Programa: R03001F9.PRG
 \ Data....: 02-08-96
 \ Sistema.: Administradora de Funer rias
 \ Funcao..: N' OP. do relat¢rio ADM_R030
 \ Analista: Ademilson Pedro Bom
 \ Criacao.: Programado manualmente pelo analistad
 \ Convert.: v5.0 em 2021081014:56:31 Fase_01
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
*/

#include "adrbig.ch"    // inicializa constantes manifestas

nucop:=2
RETU []       // <- deve retornar um valor qualquer

* \\ Final de R03001F9.PRG